repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: fix-encoding-pragma
        args: [--remove]
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--config, pyproject.toml]
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: [--settings-file, pyproject.toml]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.7.0
    hooks:
      - id: flake8
        args: [--config, .flake8]
