import pandas as pd
from sport_monks.etl_management.etls.create_clean_data_by_leagues import _transform_matches_data

RAW_DATA_MATCHES = pd.DataFrame(
    [
        {
            "match_id": 235118,
            "league_id": 564,
            "season_id": 853,
            "stage_id": 1605,
            "group_id": None,
            "aggregate_id": None,
            "round_id": 27710,
            "state_id": 5,
            "venue_id": 89,
            "name": "Espanyol vs Valencia",
            "starting_at": "2017-05-13 14:00:00",
            "result_info": "Valencia won after full-time.",
            "leg": "1/1",
            "details": None,
            "length": 90,
            "placeholder": False,
            "has_odds": True,
            "starting_at_timestamp": 1494684000,
            "formations": [
                {
                    "id": 6716,
                    "fixture_id": 235118,
                    "participant_id": 214,
                    "formation": "4-2-3-1",
                    "location": "away",
                },
                {
                    "id": 6715,
                    "fixture_id": 235118,
                    "participant_id": 528,
                    "formation": "4-4-2",
                    "location": "home",
                },
            ],
            "scores": [
                {
                    "id": 1188270,
                    "fixture_id": 235118,
                    "type_id": 2,
                    "participant_id": 528,
                    "score": {"goals": 0, "participant": "home"},
                    "description": "2ND_HALF",
                },
                {
                    "id": 1188268,
                    "fixture_id": 235118,
                    "type_id": 1,
                    "participant_id": 528,
                    "score": {"goals": 0, "participant": "home"},
                    "description": "1ST_HALF",
                },
                {
                    "id": 1188269,
                    "fixture_id": 235118,
                    "type_id": 1,
                    "participant_id": 214,
                    "score": {"goals": 0, "participant": "away"},
                    "description": "1ST_HALF",
                },
                {
                    "id": 1188271,
                    "fixture_id": 235118,
                    "type_id": 2,
                    "participant_id": 214,
                    "score": {"goals": 1, "participant": "away"},
                    "description": "2ND_HALF",
                },
                {
                    "id": 1188272,
                    "fixture_id": 235118,
                    "type_id": 1525,
                    "participant_id": 528,
                    "score": {"goals": 0, "participant": "home"},
                    "description": "CURRENT",
                },
                {
                    "id": 1188273,
                    "fixture_id": 235118,
                    "type_id": 1525,
                    "participant_id": 214,
                    "score": {"goals": 1, "participant": "away"},
                    "description": "CURRENT",
                },
            ],
            "venue": {
                "id": 89,
                "country_id": 32,
                "city_id": 20272,
                "name": "RCDE Stadium",
                "address": "Avenida Baix Llobregat 100",
                "zipcode": None,
                "latitude": "41.355724",
                "longitude": "2.0706225",
                "capacity": 40500,
                "image_path": "https://cdn.sportmonks.com/images/soccer/venues/25/89.png",
                "city_name": "Cornella de Llobregat",
                "surface": "grass",
                "national_team": False,
            },
            "lineups": [
                {
                    "id": 2441115,
                    "sport_id": 1,
                    "fixture_id": 235118,
                    "player_id": 793,
                    "team_id": 214,
                    "position_id": 26,
                    "formation_field": None,
                    "type_id": 11,
                    "formation_position": None,
                    "player_name": "Rodrigo",
                    "jersey_number": 19,
                },
                {
                    "id": 2441129,
                    "sport_id": 1,
                    "fixture_id": 235118,
                    "player_id": 186635,
                    "team_id": 214,
                    "position_id": 26,
                    "formation_field": None,
                    "type_id": 11,
                    "formation_position": None,
                    "player_name": "Álvaro Medrán",
                    "jersey_number": 20,
                },
                {
                    "id": 2440790,
                    "sport_id": 1,
                    "fixture_id": 235118,
                    "player_id": 1262,
                    "team_id": 528,
                    "position_id": 26,
                    "formation_field": None,
                    "type_id": 11,
                    "formation_position": None,
                    "player_name": "José Jurado",
                    "jersey_number": 14,
                },
                {
                    "id": 2440815,
                    "sport_id": 1,
                    "fixture_id": 235118,
                    "player_id": 129727,
                    "team_id": 528,
                    "position_id": 25,
                    "formation_field": None,
                    "type_id": 11,
                    "formation_position": None,
                    "player_name": "David López",
                    "jersey_number": 15,
                },
                {
                    "id": 2440834,
                    "sport_id": 1,
                    "fixture_id": 235118,
                    "player_id": 110226,
                    "team_id": 528,
                    "position_id": 26,
                    "formation_field": None,
                    "type_id": 11,
                    "formation_position": None,
                    "player_name": "Hernán Pérez",
                    "jersey_number": 17,
                },
            ],
            "weatherreport": None,
        }
    ]
)

RAW_DATA_TEAMS = pd.DataFrame(
    [
        {
            "team_id": 528,
            "sport_id": 1,
            "country_id": 32,
            "venue_id": 89,
            "gender": True,
            "name": "Espanyol",
            "short_code": "ESY",
            "image_path": "https://cdn.sportmonks.com/images/soccer/teams/16/528.png",
            "founded": 1900,
            "type": "domestic",
            "placeholder": False,
            "last_played_at": "2023-12-19 20:30:00",
            "players": [
                {
                    "id": 11217,
                    "transfer_id": None,
                    "player_id": 110226,
                    "team_id": 528,
                    "position_id": 26,
                    "detailed_position_id": 150,
                    "start": "2020-08-01",
                    "end": "2024-06-30",
                    "captain": False,
                    "jersey_number": 21,
                },
                {
                    "id": 370694,
                    "transfer_id": 10500,
                    "player_id": 129727,
                    "team_id": 528,
                    "position_id": 26,
                    "detailed_position_id": 153,
                    "start": "2022-08-08",
                    "end": "2027-06-30",
                    "captain": False,
                    "jersey_number": 20,
                },
            ],
        },
        {
            "team_id": 214,
            "sport_id": 1,
            "country_id": 32,
            "venue_id": 9240,
            "gender": True,
            "name": "Valencia",
            "short_code": "VAL",
            "image_path": "https://cdn.sportmonks.com/images/soccer/teams/22/214.png",
            "founded": 1919,
            "type": "domestic",
            "placeholder": False,
            "last_played_at": "2023-12-19 18:00:00",
            "players": [
                {
                    "id": 11079,
                    "transfer_id": 26154,
                    "player_id": 186635,
                    "team_id": 214,
                    "position_id": 25,
                    "detailed_position_id": 148,
                    "start": "2017-08-18",
                    "end": "2024-06-30",
                    "captain": False,
                    "jersey_number": 5,
                },
                {
                    "id": 386653,
                    "transfer_id": 11242,
                    "player_id": 793,
                    "team_id": 214,
                    "position_id": 26,
                    "detailed_position_id": 153,
                    "start": "2022-08-25",
                    "end": "2028-06-30",
                    "captain": False,
                    "jersey_number": 10,
                },
            ],
        },
    ]
)


def test_transform_matches_data():
    transformed_data = pd.DataFrame(
        [
            {"season_id": 853, "team_id": 214, "league_id": 564},
            {"season_id": 853, "team_id": 528, "league_id": 564},
        ]
    )
    result = _transform_matches_data(transformed_data, RAW_DATA_MATCHES, RAW_DATA_TEAMS)
    expected = pd.DataFrame(
        [
            {
                "season_id": 853,
                "team_id": 214,
                "league_id": 564,
                "home_matches": [],
                "away_matches": [
                    {
                        "match_id": 235118,
                        "date": "2017-05-13 14:00:00",
                        "date_timestamp": 1494684000,
                        "duration": 90,
                        "weatherreport": None,
                        "lineups": [
                            {
                                "id": 2441115,
                                "sport_id": 1,
                                "fixture_id": 235118,
                                "player_id": 793,
                                "team_id": 214,
                                "position_id": 26,
                                "formation_field": None,
                                "type_id": 11,
                                "formation_position": None,
                                "player_name": "Rodrigo",
                                "jersey_number": 19,
                            },
                            {
                                "id": 2441129,
                                "sport_id": 1,
                                "fixture_id": 235118,
                                "player_id": 186635,
                                "team_id": 214,
                                "position_id": 26,
                                "formation_field": None,
                                "type_id": 11,
                                "formation_position": None,
                                "player_name": "Álvaro Medrán",
                                "jersey_number": 20,
                            },
                            {
                                "id": 2440790,
                                "sport_id": 1,
                                "fixture_id": 235118,
                                "player_id": 1262,
                                "team_id": 528,
                                "position_id": 26,
                                "formation_field": None,
                                "type_id": 11,
                                "formation_position": None,
                                "player_name": "José Jurado",
                                "jersey_number": 14,
                            },
                            {
                                "id": 2440815,
                                "sport_id": 1,
                                "fixture_id": 235118,
                                "player_id": 129727,
                                "team_id": 528,
                                "position_id": 25,
                                "formation_field": None,
                                "type_id": 11,
                                "formation_position": None,
                                "player_name": "David López",
                                "jersey_number": 15,
                            },
                            {
                                "id": 2440834,
                                "sport_id": 1,
                                "fixture_id": 235118,
                                "player_id": 110226,
                                "team_id": 528,
                                "position_id": 26,
                                "formation_field": None,
                                "type_id": 11,
                                "formation_position": None,
                                "player_name": "Hernán Pérez",
                                "jersey_number": 17,
                            },
                        ],
                        "goals_home": 0,
                        "team_name_home": "Espanyol",
                        "team_id_home": 528,
                        "goals_away": 2,
                        "team_name_away": "Valencia",
                        "team_id_away": 214,
                    }
                ],
            },
            {
                "season_id": 853,
                "team_id": 528,
                "league_id": 564,
                "home_matches": [
                    {
                        "match_id": 235118,
                        "date": "2017-05-13 14:00:00",
                        "date_timestamp": 1494684000,
                        "duration": 90,
                        "weatherreport": None,
                        "lineups": [
                            {
                                "id": 2441115,
                                "sport_id": 1,
                                "fixture_id": 235118,
                                "player_id": 793,
                                "team_id": 214,
                                "position_id": 26,
                                "formation_field": None,
                                "type_id": 11,
                                "formation_position": None,
                                "player_name": "Rodrigo",
                                "jersey_number": 19,
                            },
                            {
                                "id": 2441129,
                                "sport_id": 1,
                                "fixture_id": 235118,
                                "player_id": 186635,
                                "team_id": 214,
                                "position_id": 26,
                                "formation_field": None,
                                "type_id": 11,
                                "formation_position": None,
                                "player_name": "Álvaro Medrán",
                                "jersey_number": 20,
                            },
                            {
                                "id": 2440790,
                                "sport_id": 1,
                                "fixture_id": 235118,
                                "player_id": 1262,
                                "team_id": 528,
                                "position_id": 26,
                                "formation_field": None,
                                "type_id": 11,
                                "formation_position": None,
                                "player_name": "José Jurado",
                                "jersey_number": 14,
                            },
                            {
                                "id": 2440815,
                                "sport_id": 1,
                                "fixture_id": 235118,
                                "player_id": 129727,
                                "team_id": 528,
                                "position_id": 25,
                                "formation_field": None,
                                "type_id": 11,
                                "formation_position": None,
                                "player_name": "David López",
                                "jersey_number": 15,
                            },
                            {
                                "id": 2440834,
                                "sport_id": 1,
                                "fixture_id": 235118,
                                "player_id": 110226,
                                "team_id": 528,
                                "position_id": 26,
                                "formation_field": None,
                                "type_id": 11,
                                "formation_position": None,
                                "player_name": "Hernán Pérez",
                                "jersey_number": 17,
                            },
                        ],
                        "goals_home": 0,
                        "team_name_home": "Espanyol",
                        "team_id_home": 528,
                        "goals_away": 2,
                        "team_name_away": "Valencia",
                        "team_id_away": 214,
                    }
                ],
                "away_matches": [],
            },
        ]
    )

    assert result.equals(expected)
